---
development:
  cloud_name: dc2vrqece
  api_key: '913524789211834'
  api_secret: "swl-1SXIblzUNOu84g_Nv-sW01w"
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dc2vrqece
  api_key: '913524789211834'
  api_secret: "swl-1SXIblzUNOu84g_Nv-sW01w"
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dc2vrqece
  api_key: '913524789211834'
  api_secret: "swl-1SXIblzUNOu84g_Nv-sW01w"
  enhance_image_tag: true
  static_file_support: false